name: ServerCore
version: 1.1
description: Core commands & utils
author: 8qBIT

main: me.qbit.core.Main

commands:
   fly:
      description: Enable or disable flights & change flight speed.
      usage: /fly or /fly <speed 0.1 - 1>
   gamemode:
      description: Change your current gamemode.
      aliases: [gm]
      usage: /gamemode <mode>
   tppos:
      description: Teleport to coordinates.
      usage: /tppos <x> <y> <z>
   vanish:
      description: Make yourself invisible from others.
      usage: /vanish
   rtp:
      description: Random teleport.
      usage: /rtp
   feed:
      description: Gives max food.
      usage: /feed
   heal:
      description: Heals you.
      usage: /heal
   teleport:
      description: Teleports you to the player.
      aliases: [tp, goto]
      usage: /teleport <name>
   discord:
      description: Gives you a discord link.
      usage: /discord
   home:
      description: Teleports you to your home.
      usage: /home <name>
   sethome:
      description: Sets a home.
      usage: /sethome <name>
   delhome:
      description: Deletes a home.
      usage: /delhome <name>
   homes:
      description: Lists your homes.
      usage: /homes
   kickall:
      description: Kicks all players connected.
      usage: /kickall <reason>
   enderchest:
      description: Opens enderchest.
      aliases: [ec]
      usage: /enderchest
   invsee:
      description: Open player inventory.
      usage: /invsee <player>
   back:
      description: Teleports you to your last location.
      usage: /back
   mute:
      description: Mutes a player.
      usage: /mute <player>
   spawn:
      description: Teleports you to the spawn.
      usage: /spawn
   tpa:
      description: Requests teleportation to a player.
      usage: /tpa <player>
   tpahere:
      description: Requests teleportation of a player to your location.
      usage: /tpahere <player>
   tpaccept:
      description: Accepts teleportation request.
      usage: /tpaccept
   tpdeny:
      description: Denies teleportation request.
      usage: /tpdeny